### ISSUE TITLE
v0.0.8 not working on Travis (v0.0.7 works in the same environment)

### ISSUE THREAD

**Issue by jlchereau** [webdriverio-boneyard/wdio-selenium-standalone-service#19]
My **[.travis.yml](https://github.com/Memba/Memba-Blog/blob/master/.travis.yml)** is:

```
sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
jdk:
  - oraclejdk8
env:
  - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "npm install -g npm"
  - "npm install -g grunt-cli"
before_script:
  - "grunt build"
```

Just changing

```
"wdio-selenium-standalone-service": "0.0.7",
```

for 

```
"wdio-selenium-standalone-service": "0.0.8",
```

in **[package.json](https://github.com/Memba/Memba-Blog/blob/master/package.json)** triggers:

```
Running "webdriver:local" (webdriver) task
A service failed in the 'onPrepare' hook
Error: Selenium server did not start.
Another Selenium process may already be running or your java version may be out of date.
Be sure to check the official Selenium release notes for minimum required java version: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG
    at ChildProcess.errorIfNeverStarted (/home/travis/build/Memba/Memba-Blog/node_modules/selenium-standalone/lib/start.js:150:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
Continue...
```

See v0.0.7 logs (working) at https://travis-ci.org/Memba/Memba-Blog/jobs/203764038#L1688,
and v0.0.8 logs (not working) at https://travis-ci.org/Memba/Memba-Blog/jobs/203760023#L1679.

As far as the error message is concerned:
- oraclejdk8 in .travis.yml here above should ensure this is using Java 8,
- If another selenium process was running v0.0.7 would also be affected, which is not the case.

**Comment by jlchereau** [comment]
I suspect this is related to https://github.com/vvo/selenium-standalone/issues/261 which prevents selenium-standalone v6.0.0 from starting. Upgrade to v6.0.1 for a fix.

**Comment by jlchereau** [comment]
Suggested fix tried above does not work.

**Comment by jlchereau** [comment]
After much digging, I have found the solution, i.e. add to .travis.yml:

```
addons:
  apt:
    packages:
      - oracle-java8-set-default
```

instead of

```
jdk:
  - oraclejdk8
```

**Note that others might benefit from an improved error message.**
